Add litecoin-core@0.21.2.1
uphold/docker-litecoin-core pull request #31
Opened 2022-07-01 13:27 UTC by alexandremandim

Add version 0.21.2.1

2022-07-04 14:51 UTC, pedrobranco requested changes

2022-07-04 14:51 UTC, pedrobranco commented on 0.21/Dockerfile
> +    FE3348877809386C \
Remove unnecessary key.

2022-07-04 14:51 UTC, pedrobranco commented on 0.21/Dockerfile
> +    B42F6819007F00F88E364FD4036A9C25BF357DD4 \
```suggestion
    3620E9D387E55666 # litecoin key \
    B42F6819007F00F88E364FD4036A9C25BF357DD4 # gosu key \
```

2022-07-04 14:51 UTC, pedrobranco commented on 0.21/Dockerfile
> +
Remove extra newline.

2022-07-04 15:17 UTC, alexandremandim commented
Do u want me to squash the 2 commits into 1?

2022-07-26 11:03 UTC, pedrobranco approved these changes

2022-07-26 11:03 UTC, merged