Add litecoin-core@0.15.0.1rc1
uphold/docker-litecoin-core pull request #8
Opened 2017-12-19 15:17 UTC by ruimarinho

2018-02-22 12:02 UTC, pedrobranco requested changes

2018-02-22 12:02 UTC, pedrobranco commented on 0.15/Dockerfile
> +RUN echo https://download.litecoin.org/litecoin-${LITECOIN_VERSION}.1rc1/linux/litecoin-${LITECOIN_VERSION}.1rc1-linux-signatures.asc
Remove this line please.

2018-02-22 12:04 UTC, pedrobranco commented
Also, add another PR to bump this Dockerfile version to `0.15.1rc1` and create the corresponding.

2018-03-08 12:35 UTC, ruimarinho commented
Replaced by https://github.com/uphold/docker-litecoin-core/pull/11/files.

2018-03-08 12:35 UTC, closed without merging